package biblioPackage;
// Generated 19 ene. 2020 17:00:06 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Autor generated by hbm2java
 */
public class Autor implements java.io.Serializable {

	private Integer idAutor;
	private String nomautor;
	private Set llibreses = new HashSet(0);

	public Autor() {
	}

	public Autor(String nomautor, Set llibreses) {
		this.nomautor = nomautor;
		this.llibreses = llibreses;
	}

	public Integer getIdAutor() {
		return this.idAutor;
	}

	public void setIdAutor(Integer idAutor) {
		this.idAutor = idAutor;
	}

	public String getNomautor() {
		return this.nomautor;
	}

	public void setNomautor(String nomautor) {
		this.nomautor = nomautor;
	}

	public Set getLlibreses() {
		return this.llibreses;
	}

	public void setLlibreses(Set llibreses) {
		this.llibreses = llibreses;
	}

	@Override
	public String toString() {
		return "Autor [idAutor=" + idAutor + ", nomautor=" + nomautor + ", llibreses=" + llibreses + "]";
	}

}
