package biblioPackage;
// Generated 19 ene. 2020 17:00:06 by Hibernate Tools 5.4.7.Final

/**
 * Biblioteca generated by hbm2java
 */
public class Biblioteca implements java.io.Serializable {

	private Integer idBiblioteca;
	private String nom;

	public Biblioteca() {
	}

	public Biblioteca(String nom) {
		this.nom = nom;
	}

	public Integer getIdBiblioteca() {
		return this.idBiblioteca;
	}

	public void setIdBiblioteca(Integer idBiblioteca) {
		this.idBiblioteca = idBiblioteca;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

}
