package biblioPackage;
// Generated 19 ene. 2020 17:00:06 by Hibernate Tools 5.4.7.Final

/**
 * Llibres generated by hbm2java
 */
public class Llibres implements java.io.Serializable {

	private Integer idLlibre;
	private Autor autor;
	private String nomLlibre;
	private String editoria;

	public Llibres() {
	}

	public Llibres(Autor autor) {
		this.autor = autor;
	}

	public Llibres(Autor autor, String nomLlibre, String editoria) {
		this.autor = autor;
		this.nomLlibre = nomLlibre;
		this.editoria = editoria;
	}

	public Integer getIdLlibre() {
		return this.idLlibre;
	}

	public void setIdLlibre(Integer idLlibre) {
		this.idLlibre = idLlibre;
	}

	public Autor getAutor() {
		return this.autor;
	}

	public void setAutor(Autor autor) {
		this.autor = autor;
	}

	public String getNomLlibre() {
		return this.nomLlibre;
	}

	public void setNomLlibre(String nomLlibre) {
		this.nomLlibre = nomLlibre;
	}

	public String getEditoria() {
		return this.editoria;
	}

	public void setEditoria(String editoria) {
		this.editoria = editoria;
	}

}
