package biblioPackage;
// Generated 19 ene. 2020 17:00:06 by Hibernate Tools 5.4.7.Final

/**
 * Persona generated by hbm2java
 */
public class Persona implements java.io.Serializable {

	private String dni;
	private String nomPersona;
	private String telefon;

	public Persona() {
	}

	public Persona(String dni) {
		this.dni = dni;
	}

	public Persona(String dni, String nomPersona, String telefon) {
		this.dni = dni;
		this.nomPersona = nomPersona;
		this.telefon = telefon;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getNomPersona() {
		return this.nomPersona;
	}

	public void setNomPersona(String nomPersona) {
		this.nomPersona = nomPersona;
	}

	public String getTelefon() {
		return this.telefon;
	}

	public void setTelefon(String telefon) {
		this.telefon = telefon;
	}

}
